Insert into dbo.Positions(Number, EvenOdd, ColorId)
values (0, 1, 4)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (1, 0, 2, 1, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (2, 1, 1, 1, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (3, 0, 2, 1, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (4, 1, 1, 1, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (5, 0, 2, 1, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (6, 1, 1, 1, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (7, 0, 2, 1, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (8, 1, 1, 1, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (9, 0, 2, 1, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (10, 1, 1, 1, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (11, 0, 1, 1, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (12, 1, 2, 1, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (13, 0, 1, 2, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (14, 1, 2, 2, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (15, 0, 1, 2, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (16, 1, 2, 2, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (17, 0, 1, 2, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (18, 1, 2, 2, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (19, 0, 2, 2, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (20, 1, 1, 2, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (21, 0, 2, 2, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (22, 1, 1, 2, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (23, 0, 2, 2, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (24, 1, 1, 2, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (25, 0, 2, 3, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (26, 1, 1, 3, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (27, 0, 2, 3, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (28, 1, 1, 3, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (29, 0, 1, 3, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (30, 1, 2, 3, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (31, 0, 1, 3, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (32, 1, 2, 3, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (33, 0, 1, 3, 3)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (34, 1, 2, 3, 1)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (35, 0, 1, 3, 2)
Insert into dbo.Positions(Number, EvenOdd, ColorId, DozenId, [Column])
values (36, 1, 2, 3, 3)

Insert into dbo.Colors (Name) values ('Black')
Insert into dbo.Colors (Name) values ('Red')
Insert into dbo.Colors (Name) values ('Blue')
Insert into dbo.Colors ([Name]) values ('Green')

Insert into dbo.Dozens (Name) values ('1')
Insert into dbo.Dozens (Name) values ('2')
Insert into dbo.Dozens (Name) values ('3')